In [1]:
from isoconversion import *
import numpy as np
from scipy.constants import R
import plotly.express as px

In [2]:
betas = [5, 10, 15, 20, 25]

In [3]:
curves = get_all_curves(betas)

In [4]:
alpha = [i/100 for i in range(5,100,5)]

In [5]:
para = []

In [6]:
for a in alpha:
    para.append(calc_parameters(a, betas, curves))

In [7]:
paras = {
    'alpha' : [i[0] for i in para],
    'Ea (kJ/mol)' : [i[1]/1000 for i in para],
    'c' : [i[2] for i in para],
    'R^2' : [i[3] for i in para]
}

In [8]:
df = pd.DataFrame(paras)
df

    alpha  Ea (kJ/mol)          c       R^2
0    0.05    81.416282  15.837769  0.948186
1    0.10   102.449168  20.689926  0.983614
2    0.15   104.131235  21.004832  0.961101
3    0.20    98.023056  19.469418  0.980196
4    0.25   102.763702  20.458130  0.983877
5    0.30   102.805602  20.359654  0.976489
6    0.35   116.490114  23.348796  0.979873
7    0.40   136.861549  27.803788  0.992686
8    0.45   144.396312  29.520472  0.993453
9    0.50   156.338241  32.161652  0.994362
10   0.55   159.574219  32.888629  0.990577
11   0.60   159.318486  32.749555  0.986698
12   0.65   158.982298  32.503604  0.985749
13   0.70   152.580115  30.927485  0.983267
14   0.75   154.473496  31.058303  0.984291
15   0.80   157.308791  31.354792  0.977748
16   0.85   164.793789  32.448080  0.976210
17   0.90   179.549112  34.805548  0.987688
18   0.95   202.156715  38.187321  0.982896